apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: whoami
  namespace: argocd
  labels:
    app: whoami
    project: workloads
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: whoami
  project: workloads
  source:
    repoURL: "https://github.com/MichielVanHerreweghe/platform-gitops.git"
    path: src/workloads/whoami/manifests
    targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - CreateNamespace=true
      - PruneLast=true
