apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbird-api-secret
  namespace: netbird
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical-secret-store
    kind: ClusterSecretStore
  target:
    name: netbird-mgmt-api-key
    creationPolicy: Owner
    template:
      data:
        NB_API_KEY: "{{ .apiKey }}"
  data:
    - secretKey: apiKey
      remoteRef:
        key: netbird-api-token