api:
  image:
    repository: ghcr.io/michielvanherreweghe/finplan-backend
    pullPolicy: IfNotPresent
frontend:
  image:
    repository: ghcr.io/michielvanherreweghe/finplan-frontend
    pullPolicy: IfNotPresent

database:
  enabled: true

networkPolicy:
  enabled: true
  gateway:
    namespace: envoy-gateway-system
    podSelector:
      gateway.envoyproxy.io/owning-gateway-name: eg
  egressFqdns:
    - matchPattern: "*.auth0.com"
