apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portfolio
  namespace: argocd
  labels:
    app: portfolio
    project: portfolio
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: portfolio
  project: portfolio
  sources:
    - repoURL: ghcr.io/michielvanherreweghe/charts
      chart: portfolio
      targetRevision: 2.1.1
      helm:
        valueFiles:
          - $values/src/workloads/portfolio/values.yaml
    - repoURL: "https://github.com/MichielVanHerreweghe/platform-gitops.git"
      targetRevision: HEAD
      ref: values
    - repoURL: "https://github.com/MichielVanHerreweghe/platform-gitops.git"
      targetRevision: HEAD
      path: src/workloads/portfolio/manifests
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - CreateNamespace=true
      - PruneLast=true