replicaCount: 2

image:
  repository: ghcr.io/michielvanherreweghe/portfolio-frontend
  tag: "1.0.1"

gateway:
  enabled: true
  parentRefs:
    - name: eg
      namespace: envoy-gateway-system
      sectionName: https-nomaddigital
  hostnames:
    - nomaddigital.dev
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /

ciliumNetworkPolicy:
  enabled: true
  ingress:
    fromGateway:
      enabled: true
      endpointSelector:
        matchLabels:
          k8s:io.kubernetes.pod.namespace: envoy-gateway-system
          gateway.envoyproxy.io/owning-gateway-name: eg

autoscaling:
  enabled: false

podDisruptionBudget:
  enabled: true
  minAvailable: 1