apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - core/project.yaml
  - core/external-secrets/application.yaml
  - core/cert-manager/application.yaml
  - core/external-dns/application.yaml
  - core/netbird/application.yaml
  - core/envoy-gateway/application.yaml
  - core/dragonflydb/application.yaml
  - core/cloudnative-pg/application.yaml
  - core/argocd/application.yaml

  - workloads/portfolio/project.yaml
  - workloads/portfolio/prod/application.yaml

  - workloads/finplan/project.yaml
  - workloads/finplan/dev/application.yaml