apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - core/project.yaml
  - core/external-secrets/application.yaml
  - core/cert-manager/application.yaml
  - core/external-dns/application.yaml
  - core/netbird/application.yaml
  - core/envoy-gateway/application.yaml
  - core/argocd/application.yaml